table 'Live Capacity Measures'
	lineageTag: e86a1c70-4496-427f-acd0-4b12299399fc

	measure 'Dog In Used' =
			
			CALCULATE(
			    COUNTROWS('ShelterBuddy Report In Care Inventory'),
			    TREATAS(
			        VALUES('Live Capacity Space Area Mapping'[Area Mapping Key]),
			        'ShelterBuddy Report In Care Inventory'[AreaMappingKey]
			    ), 'Live Capacity Space Area Mapping'[Animal Type] = "Dog"
			)
		formatString: 0
		lineageTag: c42117bc-47b9-48b4-af9c-9267abedb817

		changedProperty = IsHidden

	measure 'Cat In Used' =
			
			CALCULATE(
			    COUNTROWS('ShelterBuddy Report In Care Inventory'),
			    TREATAS(
			        VALUES('Live Capacity Space Area Mapping'[Area Mapping Key]),
			        'ShelterBuddy Report In Care Inventory'[AreaMappingKey]
			    ), 'ShelterBuddy Report In Care Inventory'[Animal Type] = "Cat"
			)
		formatString: 0
		lineageTag: 487c7631-5e3e-4be0-96d7-43675427a3d5

		changedProperty = IsHidden

	measure 'Dog Open' = [Total Dog Capacity] - [Dog In Used]
		formatString: 0
		lineageTag: 1a2d168d-8b3d-4478-8d86-d39544806b56

		changedProperty = IsHidden

	measure 'Total Dog Capacity' = ```
			sum('Live Capacity Community Animal Centres'[Total Dog Capacity]) 
			```
		formatString: 0
		lineageTag: 0ca58535-21c1-4492-a78c-dd13f25e0359

	measure 'Total Cat Capacity' = ```
			sum('Live Capacity Community Animal Centres'[Total Cat Capacity]) 
			```
		formatString: 0
		lineageTag: 61f93628-bf31-47b0-8c56-f5f80980c569

	measure 'Cat Open' = [Total Cat Capacity] - [Cat In Used]
		formatString: 0
		lineageTag: ff5e07f6-887c-4ea3-b5f7-35eb0195b050

	measure 'Dog Hold' = sum('Live Capacity Manager Update'[Dog Hold Kennels])
		formatString: 0
		lineageTag: 4d238365-b3fa-42c2-a837-899df0b3775c

	measure 'Dog Unavailable' = sum('Live Capacity Manager Update'[Dog Unavailable Kennels])
		formatString: 0
		lineageTag: 1eb0dc5c-4cd8-4a45-a708-9f177d601469

	measure 'Cat Hold' = sum('Live Capacity Manager Update'[Cat Hold Portals])
		formatString: 0
		lineageTag: b72615be-6580-4313-bbad-1b05c8e8d35c

	measure 'Cat Unavailable' = sum('Live Capacity Manager Update'[Cat Unavailable Portals])
		formatString: 0
		lineageTag: 51934da2-79c9-4ac9-a257-9ffc0422d05e

	measure 'Animal Flow Dog Open' = [Total Dog Capacity] - [Dog In Used] - [Dog Hold] - [Dog Unavailable]
		formatString: 0
		lineageTag: 7748fea3-e2ae-4a20-aaa5-02d67405d10b

	partition 'Live Capacity Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

